"use client";
import{useCallback,useEffect,useState}from"react";
type Patient={participantId:string;studyId:string;displayName:string;status:string;alert:{id:string;priority:"URGENT"|"ATTENTION_NEEDED";status:string;summary:string}|null;audit:{id:string;action:string;createdAt:string}[]};
const staffHeaders={"content-type":"application/json","x-compass-dev-role":"staff"};
export default function Alerts(){
 const[patients,setPatients]=useState<Patient[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[deviceCode,setDeviceCode]=useState("");
 const refresh=useCallback(async()=>{try{const response=await fetch("/api/staff/patients",{headers:{"x-compass-dev-role":"staff"}}),payload=await response.json();if(!response.ok)throw new Error(payload.message);setPatients(payload.data);setError("")}catch(reason){setError(reason instanceof Error?reason.message:"Patients could not be loaded.")}finally{setLoading(false)}},[]);
 useEffect(()=>{void fetch("/api/staff/patients",{headers:{"x-compass-dev-role":"staff"}}).then(async response=>{const payload=await response.json();if(!response.ok)throw new Error(payload.message);return payload.data}).then(data=>{setPatients(data);setError("")}).catch(reason=>setError(reason instanceof Error?reason.message:"Patients could not be loaded.")).finally(()=>setLoading(false))},[]);
 async function post(url:string,body?:object){const response=await fetch(url,{method:"POST",headers:staffHeaders,body:body?JSON.stringify(body):undefined}),payload=await response.json();if(!response.ok)throw new Error(payload.message);return payload.data;}
 async function act(patient:Patient,action:"claim"|"close"){if(!patient.alert)return;try{await post(`/api/staff/alerts/${patient.alert.id}/${action}`,action==="close"?{outcome:"Synthetic follow-up completed"}:undefined);await refresh()}catch(reason){setError(reason instanceof Error?reason.message:"Alert action failed.")}}
 async function newOccurrence(participantId:string){try{await post("/api/dev/occurrences",{participantId});await refresh()}catch(reason){setError(reason instanceof Error?reason.message:"Occurrence could not be created.")}}
 async function newDeviceCode(participantId:string){try{const data=await post("/api/dev/activation-codes",{participantId});setDeviceCode(data.activationCode)}catch(reason){setError(reason instanceof Error?reason.message:"Device code could not be created.")}}
 return <main><p className="eyebrow">Nurse dashboard</p><h1>Prioritized patients</h1>{error&&<p className="card" role="alert" style={{color:"#9b2415"}}>{error}</p>}{deviceCode&&<div className="card"><b>Synthetic device activation code (shown once):</b> {deviceCode}</div>}{loading?<div className="card"><h2>Loading patients…</h2></div>:patients.length===0?<div className="card"><h2>No enrolled patients</h2></div>:<div className="grid">{patients.map(patient=><div className="card grid" key={patient.participantId}><div>{patient.alert?<><span className={`pill ${patient.alert.priority==="URGENT"?"urgent":""}`}>{patient.alert.priority==="URGENT"?"Urgent":"Attention needed"}</span> <span className="pill">{patient.alert.status.replace("_"," ")}</span></>:<span className="pill">Stable</span>}</div><h2>{patient.displayName} · {patient.studyId}</h2>{patient.alert&&<p>{patient.alert.summary}</p>}{patient.alert?.status==="NEW"&&<button className="btn" onClick={()=>void act(patient,"claim")}>Claim alert</button>}{patient.alert?.status==="IN_PROGRESS"&&<button className="btn" onClick={()=>void act(patient,"close")}>Close: follow-up completed</button>}<button className="btn secondary" onClick={()=>void newOccurrence(patient.participantId)}>Create synthetic test check-in</button><button className="btn secondary" onClick={()=>void newDeviceCode(patient.participantId)}>Issue synthetic device code</button><details><summary>Persistent audit history</summary>{patient.audit.map(event=><p key={event.id}>{new Date(event.createdAt).toLocaleString()} — {event.action}</p>)}</details></div>)}</div>}</main>;
}
